ref:
  ncbi_dmel:
    genomic_fna: Reference/ncbi_dmel.genomic.fna.gz
    genomic_gtf: Reference/ncbi_dmel.genomic.gtf.gz
    rna_from_genomic: Reference/ncbi_dmel.rna_from_genomic.fna.gz

fastqs:
  short_paired_end:
    ISO1:
      1: [FASTQS/SRR10728584_1.fastq.gz, FASTQS/SRR10728584_2.fastq.gz]
  long:
    ISO1:
      1: FASTQS/SRR10238607.fastq.gz
