ref:
  ncbi_dmel:
    genomic_fna: Downloads/ncbi_dmel.genomic.fna.gz
    genomic_gtf: Downloads/ncbi_dmel.genomic.gtf.gz
    rna_from_genomic: Downloads/ncbi_dmel.rna_from_genomic.fna.gz

fastqs:
  ISO1:
    short_paired_end:
      1:
        1: Downloads/SRR10728584_1.fastq.gz
        2: Downloads/SRR10728584_2.fastq.gz
    pacbio_hifi:
      1: Downloads/SRR10238607.fastq.gz

scripts_directory:
