#Please update the filenames of
#the gzipped genome fasta file and
#the gzipped transcriptome fasta file.
ref:
  "ncbi_dmel":
    genome: Downloads/ncbi_dmel.genome.fna.gz
    transcriptome: Downloads/ncbi_dmel.transcriptome.fna.gz

#Please update the filenames of any sequencing data you have.
#Feel free to add as many samples as you want to analyze.
#Possible sequencing data types include:
#"short" for short paired-end sequencing
#"pacbio_hifi" for PacBio HiFi data
#"pacbio_clr" for PacBio CLR data
#"ont" for Oxford Nanopore data
fastqs:
  "ISO1":
    short:
      1:
        1: Downloads/SRR10728584_1.fastq.gz
        2: Downloads/SRR10728584_2.fastq.gz
    pacbio_hifi:
      1: Downloads/SRR10238607.fastq.gz

#If the reference genome has weird chromosome names,
#edit this section with a mapping from the weird
#chromosome names to the nice chromosome names.
chroms:
  NC_004354.4: "X"
  NT_033779.5: "2L"
  NT_033778.4: "2R"
  NT_037436.4: "3L"
  NT_033777.3: "3R"
  NC_004353.4: "4"
  NC_024512.1: "Y"
  NC_024511.2: "MT"

#Advanced parameters

#For both short and long reads, we require at least read_support
#supporting reads/read pairs before we say that there is
#sufficient evidence that a particular exon-exon junction
#on a parent gene transcript is part of a retrogene.
read_support: 10

#A supporting alignment must extend at least
#junction_overhang base pairs on both
#sides of an exon-exon junction.
junction_overhang: 10

#A supporting alignment must have no more than
#max_insertions base pairs marked as insertions
#in the region comprised of the junction_overhang
#base pairs on either side of an exon-exon junction.
max_insertions: 10
